### ISSUE TITLE
Question: Will this be the new regex implementation for Go?

### ISSUE THREAD

**Issue by Dynom** [samthor/sre2#1]
Hi,

I'm curious if this project is on the roadmap for being the replacement of https://golang.org/pkg/regexp/ ?

**Comment by samthor** [comment]
Nope, it is not. It is a separate implementation of the RE2 spec, which while algorithmically similar to the regexp package, is very different and (probably usually) slower.

If it works for your use case, then I'm very glad, but otherwise there are no future plans for this code.
